In [1]:
# NumPy for AI - Mini Project Assignment

import numpy as np

# Step 1: Create Dataset

# Columns: Math, Science, English, Computer
X = np.array([
    [78, 85, 80, 90],
    [45, 50, 40, 55],
    [88, 92, 84, 95],
    [60, 70, 65, 72],
    [35, 40, 38, 45],
    [95, 98, 96, 99],
    [55, 58, 60, 62],
    [82, 79, 85, 88],
    [48, 52, 50, 46],
    [73, 75, 78, 80]
])

# Result Labels
# 1 = Pass, 0 = Fail
y = np.array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1])

print("Dataset (X):\n", X)
print("\nLabels (y):\n", y)

# Step 2: Average, Maximum, Minimum

print("\nAverage Marks:", np.mean(X, axis=0))
print("Maximum Marks:", np.max(X, axis=0))
print("Minimum Marks:", np.min(X, axis=0))

# Step 3: Count Passed and Failed

passed = np.sum(y == 1)
failed = np.sum(y == 0)

print("\nNumber of Passed Students:", passed)
print("Number of Failed Students:", failed)

# Step 4: Students Scoring Above 80 and Below 50

above_80 = X[np.any(X > 80, axis=1)]
below_50 = X[np.any(X < 50, axis=1)]

print("\nStudents Scoring Above 80:\n", above_80)
print("\nStudents Scoring Below 50:\n", below_50)

# Step 5: Normalize Dataset

# Formula: (X - min) / (max - min)

X_normalized = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

print("\nNormalized Dataset:\n", X_normalized)

# Step 6: Simple Prediction Logic
# If average marks >= 60 → Pass
# Else → Fail

average_marks = np.mean(X, axis=1)

predictions = np.where(average_marks >= 60, 1, 0)

print("\nAverage Marks of Each Student:\n", average_marks)
print("\nPredictions:\n", predictions)

# Step 7: Accuracy Calculation

accuracy = np.mean(predictions == y) * 100

print("\nAccuracy:", accuracy, "%")

Dataset (X):
 [[78 85 80 90]
 [45 50 40 55]
 [88 92 84 95]
 [60 70 65 72]
 [35 40 38 45]
 [95 98 96 99]
 [55 58 60 62]
 [82 79 85 88]
 [48 52 50 46]
 [73 75 78 80]]

Labels (y):
 [1 0 1 1 0 1 1 1 0 1]

Average Marks: [65.9 69.9 67.6 73.2]
Maximum Marks: [95 98 96 99]
Minimum Marks: [35 40 38 45]

Number of Passed Students: 7
Number of Failed Students: 3

Students Scoring Above 80:
 [[78 85 80 90]
 [88 92 84 95]
 [95 98 96 99]
 [82 79 85 88]]

Students Scoring Below 50:
 [[45 50 40 55]
 [35 40 38 45]
 [48 52 50 46]]

Normalized Dataset:
 [[0.71666667 0.77586207 0.72413793 0.83333333]
 [0.16666667 0.17241379 0.03448276 0.18518519]
 [0.88333333 0.89655172 0.79310345 0.92592593]
 [0.41666667 0.51724138 0.46551724 0.5       ]
 [0.         0.         0.         0.        ]
 [1.         1.         1.         1.        ]
 [0.33333333 0.31034483 0.37931034 0.31481481]
 [0.78333333 0.67241379 0.81034483 0.7962963 ]
 [0.21666667 0.20689655 0.20689655 0.01851852]
 [0.63333333 0.60344828 0.68965517