In [1]:
# task 1
import numpy as np

# 1. Create a 1D NumPy array containing values from 1 to 10
array1 = np.arange(1, 11)

# 2. Create a 2D array of size 3×3
array2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 3. Create an array of zeros of size 4×4
zeros_array = np.zeros((4, 4))

# 4. Create an array of ones of size 2×5
ones_array = np.ones((2, 5))

# 5. Display all arrays
print("1D Array:")
print(array1)

print("\n2D Array (3x3):")
print(array2)

print("\nZeros Array (4x4):")
print(zeros_array)

print("\nOnes Array (2x5):")
print(ones_array)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2D Array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros Array (4x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array (2x5):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
# task 2
import numpy as np

# Create a 2D array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 1. Find the shape of the array
print("Shape of array:", array_2d.shape)

# 2. Find total number of elements
print("Total elements:", array_2d.size)

# 3. Find the data type of elements
print("Data type:", array_2d.dtype)

# 4. Find the number of dimensions
print("Number of dimensions:", array_2d.ndim)

print("Shape is important in AI because it tells how data is organized and helps AI models process data correctly.")

Shape of array: (3, 3)
Total elements: 9
Data type: int64
Number of dimensions: 2
Shape is important in AI because it tells how data is organized and helps AI models process data correctly.


In [3]:
# task 3
import numpy as np

# 1. Create array
arr = np.array([10, 20, 30, 40, 50, 60])

# 2. Access elements
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Third element:", arr[2])

# 3. Print values greater than 30
print("Values greater than 30:", arr[arr > 30])

First element: 10
Last element: 60
Third element: 30
Values greater than 30: [40 50 60]


In [4]:
# task 5
import numpy as np

# 1. Create array
arr = np.array([1, 2, 3, 4, 5])

# 2. Multiply all elements by 5
print("Multiply by 5:", arr * 5)

# 3. Add 10 to all elements
print("Add 10:", arr + 10)

# 4. Square all elements
print("Squared values:", arr ** 2)

# 5. Why vectorization is important in AI
print("Vectorization is important in AI because it makes calculations faster and reduces the need for loops.")


Multiply by 5: [ 5 10 15 20 25]
Add 10: [11 12 13 14 15]
Squared values: [ 1  4  9 16 25]
Vectorization is important in AI because it makes calculations faster and reduces the need for loops.


In [5]:
# task 6
import numpy as np

# 1. Create a 2x3 array
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 2. Add 10 using broadcasting
print("After adding 10:")
print(arr2d + 10)

# 3. Multiply entire array by 2
print("After multiplying by 2:")
print(arr2d * 2)

# 4. Why broadcasting is important in machine learning
print("Broadcasting helps perform operations on arrays of different sizes quickly and efficiently.")

After adding 10:
[[11 12 13]
 [14 15 16]]
After multiplying by 2:
[[ 2  4  6]
 [ 8 10 12]]
Broadcasting helps perform operations on arrays of different sizes quickly and efficiently.


In [6]:
# task 7
import numpy as np

# 1. Create two 2x2 matrices
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

# 2. Addition
addition = matrix1 + matrix2

# 3. Subtraction
subtraction = matrix1 - matrix2

# Display results
print("Matrix Addition:")
print(addition)

print("Matrix Subtraction:")
print(subtraction)

Matrix Addition:
[[ 6  8]
 [10 12]]
Matrix Subtraction:
[[-4 -4]
 [-4 -4]]


In [7]:
# task 8
import numpy as np

# 1. Create two matrices
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

# 2. Matrix multiplication using np.dot()
result = np.dot(matrix1, matrix2)

print("Matrix Multiplication:")
print(result)

# 3. Transpose of matrix1
print("Transpose of Matrix1:")
print(matrix1.T)

# 4. Relation with neural networks
print("Matrix multiplication is used in neural networks to combine inputs, weights, and outputs efficiently.")

Matrix Multiplication:
[[19 22]
 [43 50]]
Transpose of Matrix1:
[[1 3]
 [2 4]]
Matrix multiplication is used in neural networks to combine inputs, weights, and outputs efficiently.


In [8]:
# task 9
import numpy as np

# 1. Random integer array
arr = np.random.randint(1, 101, size=(4, 4))

print("Random Integer Array:")
print(arr)

# 2. Random decimal values
decimal_arr = np.random.rand(4, 4)

print("Random Decimal Array:")
print(decimal_arr)

# 3. Maximum, minimum, average
print("Maximum Value:", arr.max())
print("Minimum Value:", arr.min())
print("Average Value:", arr.mean())

# 4. Importance in AI
print("Random numbers help initialize models, shuffle data, and improve AI training.")

Random Integer Array:
[[76 98 67 44]
 [67 63 91 42]
 [47 39 84 29]
 [ 9 79 63 25]]
Random Decimal Array:
[[0.94273914 0.41664086 0.57012633 0.9121536 ]
 [0.40480747 0.42886711 0.62805931 0.62623975]
 [0.35461518 0.22798744 0.76524575 0.39771717]
 [0.30336571 0.26120593 0.97891499 0.47385597]]
Maximum Value: 98
Minimum Value: 9
Average Value: 57.6875
Random numbers help initialize models, shuffle data, and improve AI training.


In [9]:
# task 10
import numpy as np

# 1. Marks of 10 students
marks = np.array([45, 78, 90, 56, 88, 34, 67, 92, 49, 81])

# 2. Average, highest, lowest
print("Average Marks:", marks.mean())
print("Highest Marks:", marks.max())
print("Lowest Marks:", marks.min())

# 3. Students scoring above 80
print("Students scoring above 80:", len(marks[marks > 80]))

# 4. Students failed below 50
print("Failed Students Marks:", marks[marks < 50])

Average Marks: 68.0
Highest Marks: 92
Lowest Marks: 34
Students scoring above 80: 4
Failed Students Marks: [45 34 49]


In [10]:
# task 11
import numpy as np

# 1. Random 5x5 image pixels
image = np.random.randint(0, 256, size=(5, 5))

print("Image Pixels:")
print(image)

# 2. Brightest, darkest, shape
print("Brightest Pixel:", image.max())
print("Darkest Pixel:", image.min())
print("Image Shape:", image.shape)

# 3. AI and images
print("AI reads images as arrays of pixel values where each number represents brightness or color.")

Image Pixels:
[[138  86  16 254  97]
 [108 174 222 138 253]
 [212  15  67 105 143]
 [226  91 224 132  67]
 [134  79 214  30 169]]
Brightest Pixel: 254
Darkest Pixel: 15
Image Shape: (5, 5)
AI reads images as arrays of pixel values where each number represents brightness or color.


In [11]:
# task 12
import numpy as np

# 1. Numerical data
data = np.array([10, 20, 30, 40, 50])

# 2. Normalize dataset
normalized = (data - data.min()) / (data.max() - data.min())

# 3. Print normalized values
print("Normalized Values:")
print(normalized)

# 4. Importance in AI
print("Normalization improves AI performance by keeping values in the same range and speeding up learning.")

Normalized Values:
[0.   0.25 0.5  0.75 1.  ]
Normalization improves AI performance by keeping values in the same range and speeding up learning.


In [12]:
# task 13
import numpy as np

# Dataset: Age, Salary, Purchased Product
dataset = np.array([
    [22, 25000, 0],
    [25, 30000, 1],
    [30, 45000, 1],
    [35, 50000, 0],
    [40, 65000, 1]
])

# 1. Convert into NumPy array
print("Dataset:")
print(dataset)

# 2. Separate input features and output labels
X = dataset[:, :2]
y = dataset[:, 2]

print("Input Features:")
print(X)

print("Output Labels:")
print(y)

# 3. Average salary
print("Average Salary:", X[:, 1].mean())

# 4. Highest age
print("Highest Age:", X[:, 0].max())

# 5. Dataset shape
print("Dataset Shape:", dataset.shape)

Dataset:
[[   22 25000     0]
 [   25 30000     1]
 [   30 45000     1]
 [   35 50000     0]
 [   40 65000     1]]
Input Features:
[[   22 25000]
 [   25 30000]
 [   30 45000]
 [   35 50000]
 [   40 65000]]
Output Labels:
[0 1 1 0 1]
Average Salary: 43000.0
Highest Age: 40
Dataset Shape: (5, 3)
